global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: auth-backend
    metrics_path: /metrics
    static_configs:
      - targets: ['auth-backend:8005']
        labels:
          service: auth-backend
  - job_name: usr_manag
    metrics_path: /metrics
    static_configs:
      - targets: ['usr-manag:4000']
        labels:
          service: usr-manag
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: node-exporter
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: cadvisor
          
  - job_name: frontend
    metrics_path: /metrics
    static_configs:
      - targets: ['frontend:3010']
        labels:
          service: frontend
  - job_name: chat
    metrics_path: /metrics
    static_configs:
      - targets: ['chat:8006']
        labels:
          service: chat

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alerts.yml